id: Armis Device Enrichment
version: -1
name: Armis Device Enrichment
description: Enrich Armis Alert with Device in context details
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7cfa3cf6-82b0-452f-8c52-85355d20008a
    type: start
    task:
      id: 7cfa3cf6-82b0-452f-8c52-85355d20008a
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 20,
          "y": -30
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 09a9f8b9-a40e-471b-85eb-a4123af13ebc
    type: title
    task:
      id: 09a9f8b9-a40e-471b-85eb-a4123af13ebc
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -150,
          "y": 1050
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: bfb84d23-6da9-4655-83d1-bfa8cefa9b91
    type: condition
    task:
      id: bfb84d23-6da9-4655-83d1-bfa8cefa9b91
      version: -1
      name: Was a device linked to the Armis alert?
      description: Check if there was any machine match to the hostname
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Armis.SearchAlerts.deviceIds
            iscontext: true
    view: |-
      {
        "position": {
          "x": 370,
          "y": 520
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: ef5ea2c0-95e9-41bd-881d-cb951015b84f
    type: regular
    task:
      id: ef5ea2c0-95e9-41bd-881d-cb951015b84f
      version: -1
      name: Get device information from Armis
      description: Search Devices by identifiers
      script: '|||armis-search-devices'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      device_id:
        simple: ${Armis.SearchAlerts.deviceIds}
      device_type: {}
      ip_address: {}
      mac_address: {}
      name: {}
      risk_level: {}
      time_frame: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 510,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Device Name
      output:
        simple: ${Armis.SearchDevices.name}
    - incidentfield: Device Model
      output:
        simple: ${Armis.SearchDevices.model}
    - incidentfield: Armis Device Risk Level
      output:
        simple: ${Armis.SearchDevices.riskLevel}
    - incidentfield: Device Local IP
      output:
        simple: ${Armis.SearchDevices.ipv6}
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 9766026b-b669-43bf-864d-da5b47516df2
    type: regular
    task:
      id: 9766026b-b669-43bf-864d-da5b47516df2
      version: -1
      name: Get device ID
      description: Search Armis Alerts.
      script: '|||armis-search-alerts'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      alert_id:
        simple: ${inputs.Alert_ID}
      alert_type: {}
      max_results: {}
      severity: {}
      status: {}
      time_frame: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 370,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 8ddf98ea-3c70-4cd5-8b9d-0e1207feeef6
    type: condition
    task:
      id: 8ddf98ea-3c70-4cd5-8b9d-0e1207feeef6
      version: -1
      name: Is Alert ID Valid?
      description: Check if the Alert ID is valid
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.Alert_ID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 40,
          "y": 150
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 8bda632c-4c0d-4d82-8f6f-45ddb22bcc94
    type: regular
    task:
      id: 8bda632c-4c0d-4d82-8f6f-45ddb22bcc94
      version: -1
      name: Add device data to evidence board
      description: |
        Adds provided entries to the incident Evidence Board. In playbook, can be positioned after a task to add the previous task's entries to Evidence Board automatically (with no need to provide arguments)
      scriptName: AddEvidence
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      desc: {}
      description: {}
      entryIDs: {}
      occurred: {}
      tags: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 910
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1145,
        "width": 1040,
        "x": -150,
        "y": -30
      }
    }
  }
inputs:
- key: Alert_ID
  value:
    simple: ${incident.armisalertid}
  required: true
  description: Getting the alert ID which triggered the call for the playbook
  playbookInputQuery:
outputs:
- contextPath: Device ID
  description: Device ID
  type: string
tests:
- No tests (auto formatted)
fromversion: 5.0.0
